---
- name: Converge
  hosts: setup
  gather_facts: true
  vars_files: 
  - ../../group_vars/all.yaml
  roles: 
    - role: "{{ playbook_dir }}/../../debug"
    - role: "{{ playbook_dir }}/../../security"